Donʼt pass None for headers or cookies to Request constructor
Doing this causes an error if the request.headers property is accessed:

```
Traceback (most recent call last):
  File "/usr/lib/python3.7/pdb.py", line 1701, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python3.7/pdb.py", line 1570, in _runscript
    self.run(statement)
  File "/usr/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/aecay/work/id-mite-nft/mite_id/oogway/collect_responses.py", line 3, in <module>
    from mite.test import run_single_journey, http_spy
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/aecay/work/id-mite-nft/mite_id/oogway/collect_responses.py", line 86, in do
    'request.headers': response.request.headers,
  File "/home/aecay/work/mite/acurl/acurl/__init__.py", line 159, in headers
    return dict(header.split(': ', 1) for header in self.header_list)
TypeError: 'NoneType' object is not iterable
```